# Generated by Django 3.2.12 on 2022-04-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('irma', '0001_initial'), ('irma', '0002_rename_irma_service_irmaconfig__service'), ('irma', '0003_rename__service_irmaconfig_service'), ('irma', '0004_rename_service_irmaconfig__service')]

    dependencies = [
        ('zgw_consumers', '0015_auto_20220307_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrmaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_service', models.OneToOneField(limit_choices_to={'api_type': 'orc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgw_consumers.service', verbose_name='Irma API')),
            ],
            options={
                'verbose_name': 'Irma configuration',
            },
        ),
    ]
