# Generated by Django 3.2.12 on 2022-04-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irmaconfig',
            old_name='irma_service',
            new_name='_service',
        ),
    ]
