# Generated by Django 3.2.12 on 2022-04-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irma', '0002_rename_irma_service_irmaconfig__service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irmaconfig',
            old_name='_service',
            new_name='service',
        ),
    ]
